//  __NAME__.swift
//  Generated by vegen
//  Clean Architecture Theme Definitions

import SwiftUI

extension Color {
 
    
  static let appColors = AppColors()
}

struct AppColors {
     let primaryColor = Color("AccentColor")
     let backgroundColor = Color("BackgroundColor")
    let tertiaryColor = Color("TertiaryColor")
    let darkPrimary = Color("DarkPrimary")
    
}


