//  __NAME__.swift
//  Generated by vegen
//  Clean Architecture Theme Definitions

import SwiftUI

enum AppTheme {
    static let primary = Color.orange
    static let secondary = Color.gray
    
    enum Colors {
        static let background = Color("Background")
        static let surfaceHigh = Color("SurfaceHigh")
        static let surfaceLow = Color("SurfaceLow")
        static let textPrimary = Color("TextPrimary")
        static let textSecondary = Color("TextSecondary")
    }

    enum Typography {
        static let displayLarge = Font.system(size: 32, weight: .bold, design: .default)
        static let headlineMedium = Font.system(size: 24, weight: .semibold, design: .default)
        static let bodyDefault = Font.system(size: 16, weight: .regular, design: .default)
        static let labelCaps = Font.system(size: 12, weight: .medium, design: .default).smallCaps()
    }
}

// Preview color scheme testing stub
#Preview {
    VStack(spacing: 20) {
        Text("Light Mode").environment(\.colorScheme, .light)
        Text("Dark Mode").environment(\.colorScheme, .dark)
    }
    .font(AppTheme.Typography.headlineMedium)
    .foregroundColor(AppTheme.primary)
}